/**
 * SINGLE SOURCE OF TRUTH for resume + portfolio.
 *
 * Everything recruiter-facing (portfolio sections AND the downloadable PDF,
 * generated by scripts/generate_resume.py) should be derived from this file so
 * the website and résumé never drift apart. Keep it truthful.
 */

export const PROFILE = {
  name: "Mihir Borsaniya",
  title: "Full Stack Engineer",
  tagline: "Building enterprise ERP & multi-tenant SaaS systems that scale.",
  location: "Surat, Gujarat, India",
  email: "developermihir13@gmail.com",
  phone: "+91 75758 96243",
  github: "https://github.com/MihirStack",
  githubHandle: "MihirStack",
  linkedin: "https://linkedin.com/in/mihirborsaniya",
  linkedinHandle: "mihirborsaniya",
  yearsExperience: "3+",
};

/** Professional summary — max 5 lines, ATS + recruiter friendly. */
export const SUMMARY =
  "Full Stack Engineer with 3+ years building and owning production ERP and multi-tenant SaaS platforms end to end — from API and schema design through deployment. " +
  "Currently architecting AksharPOS, a multi-tenant SaaS product, with per-tenant database isolation and dynamic, cached connection routing. " +
  "I work across Node.js, Express, React, TypeScript, and MySQL, with hands-on payment-gateway (Razorpay, Stripe, PayPal), messaging (WhatsApp Business API, Firebase, Socket.IO), and real-time integrations. " +
  "I own Linux/NGINX/PM2 deployments with GitHub Actions CI/CD, and focus on secure, performant systems — JWT/RBAC, query and cache optimization, and zero-downtime releases.";

export type Experience = {
  id: string;
  company: string;
  monogram: string;
  role: string;
  period: string;
  duration: string;
  location: string;
  focus: string;
  description: string;
  current?: boolean;
  color: string;
  summary: string;
  responsibilities: string[];
  achievements: string[];
  businessImpact: string;
  tech: string[];
};

export const EXPERIENCES: Experience[] = [
  {
    id: "aksharpos",
    company: "Codebrain Infotech → Logicode Software LLP",
    monogram: "A",
    role: "Full Stack Engineer — AksharPOS Product",
    period: "Aug 2025 — Present",
    duration: "Current",
    location: "Surat, Gujarat",
    focus: "Enterprise ERP & Multi-Tenant SaaS",
    description:
      "Product company building enterprise ERP and SaaS platforms. Registered as Logicode Software LLP in Jan 2026 — same team, same product throughout.",
    current: true,
    color: "#6366f1",
    summary:
      "Architecting AksharPOS — a multi-tenant ERP SaaS platform serving retail, wholesale, and POS businesses with isolated per-tenant databases behind a shared, secured API layer, plus an 18-template WhatsApp Business API messaging integration.",
    responsibilities: [
      "Architect multi-tenant SaaS infrastructure with dynamic, LRU-cached per-tenant database routing.",
      "Develop and document REST APIs powering the AksharPOS ERP platform.",
      "Implement JWT authentication and module-level role-based access control (RBAC).",
      "Design an 18-template WhatsApp Business API library via Meta Business Manager for transactional and marketing messaging.",
      "Integrate Razorpay payment flows with secure webhook verification.",
      "Own production deployment on Linux VPS with NGINX, PM2 cluster mode, and GitHub Actions CI/CD.",
    ],
    achievements: [
      "Modeled 50+ normalized MySQL tables backing 10+ integrated ERP modules.",
      "Navigated Meta's approval workflow to get transactional WhatsApp templates classified as Utility rather than Marketing.",
      "Reduced database load under concurrent multi-branch traffic with Redis caching on hot-path queries.",
    ],
    businessImpact:
      "Powers live retail, wholesale, and POS businesses on a single isolated multi-tenant platform.",
    tech: [
      "Node.js",
      "Express.js",
      "React.js",
      "TypeScript",
      "MySQL",
      "Redis",
      "Sequelize",
      "JWT",
      "RBAC",
      "Razorpay",
      "WhatsApp Business API",
      "NGINX",
      "PM2",
      "GitHub Actions",
    ],
  },
  {
    id: "codebrain-service",
    company: "Codebrain Infotech",
    monogram: "C",
    role: "Full Stack Developer — Service-Based",
    period: "Jul 2025 (1 month)",
    duration: "1 mo",
    location: "Surat, Gujarat",
    focus: "Client Development",
    description: "IT services company delivering client projects before transitioning to product work.",
    color: "#06b6d4",
    summary:
      "One month of service-based client development work before transitioning to full-time product engineering on AksharPOS.",
    responsibilities: [
      "Delivered client development work under Codebrain Infotech's service engagements.",
    ],
    achievements: [
      "Transitioned to full-time product engineering on AksharPOS after one month.",
    ],
    businessImpact: "Bridged into full-time product engineering on AksharPOS.",
    tech: ["Node.js", "Express.js", "React.js", "MySQL"],
  },
  {
    id: "di-solutions",
    company: "DI Solutions",
    monogram: "D",
    role: "Full Stack Developer",
    period: "Jul 2023 — Jun 2025",
    duration: "2 yrs",
    location: "Surat, Gujarat",
    focus: "HRMS, Manufacturing & Medical ERP, Real-Time Chat",
    description: "Software company delivering ERP, HRMS, and e-commerce solutions across industries.",
    color: "#8b5cf6",
    summary:
      "Delivered four major production systems: an HRMS with role-aware dashboards and Firebase notifications, a Manufacturing & Logistics ERP, a Medical Record system with e-commerce features, and a real-time subscription-based chat platform.",
    responsibilities: [
      "Built an HRMS covering attendance, leave, and employee management with role-aware dashboards and Firebase Cloud Messaging notifications.",
      "Delivered a Manufacturing & Logistics ERP covering scrap processing, shipment, cargo, sales, and inventory.",
      "Built a Medical Record system with e-commerce features for category-wise medicine management.",
      "Developed a real-time, subscription-based chat platform using Socket.IO.",
      "Built REST APIs, inventory, purchase, sales, shipment, and logistics features with React, Node.js, Express, and Sequelize/MySQL, following MVC architecture.",
      "Integrated Razorpay, Stripe, and PayPal for checkout flows; documented APIs with Swagger.",
    ],
    achievements: [
      "Delivered four major production systems spanning HRMS, manufacturing, medical/e-commerce, and real-time chat.",
      "Integrated Razorpay, Stripe, and PayPal for multi-gateway, multi-region checkout.",
      "Built real-time order, inventory, and chat updates using Socket.IO and Firebase.",
    ],
    businessImpact:
      "Enabled clients across industries to run HR, sales, inventory, and shipment operations digitally.",
    tech: [
      "Node.js",
      "Express.js",
      "React.js",
      "MySQL",
      "Sequelize",
      "JWT",
      "RBAC",
      "Socket.IO",
      "Firebase",
      "Stripe",
      "Razorpay",
      "PayPal",
      "Swagger",
      "Git",
    ],
  },
];

export type FlagshipProject = {
  id: string;
  name: string;
  company: string;
  problem: string;
  solution: string;
  architecture: string;
  features: string[];
  tech: string[];
  impact: string;
};

export const FLAGSHIP_PROJECTS: FlagshipProject[] = [
  {
    id: "aksharpos",
    name: "AksharPOS ERP",
    company: "Logicode Software LLP",
    problem:
      "Serve many retail and POS businesses on one platform with fully isolated data and per-business configuration — without running a separate server per client.",
    solution:
      "A hybrid multi-tenant model: a shared API layer with per-tenant MySQL databases, routed dynamically from the tenant identifier in the JWT.",
    architecture:
      "TenantResolver middleware resolves each request to an LRU-cached Sequelize connection; a master DB holds the tenant registry; JWT + module-level RBAC secures every route.",
    features: [
      "POS Billing",
      "Inventory",
      "Purchase",
      "Sales",
      "Customer & Supplier",
      "Branch Management",
      "Loyalty",
      "Payments",
      "Reporting & Analytics",
    ],
    tech: [
      "Node.js",
      "Express.js",
      "React.js",
      "MySQL",
      "Sequelize",
      "Redis",
      "JWT",
      "RBAC",
      "Razorpay",
      "NGINX",
      "PM2",
      "GitHub Actions",
    ],
    impact:
      "50+ data models, 10+ modules, sub-30-second tenant onboarding, running live in production.",
  },
  {
    id: "hrms",
    name: "HRMS Platform",
    company: "Codebrain Infotech",
    problem:
      "Manual attendance, leave, and employee tracking slowed HR operations and lacked real-time visibility.",
    solution:
      "A web HRMS with role-aware dashboards and Firebase-powered notifications for attendance, leave, and employee management.",
    architecture:
      "React + Redux Toolkit / React Query frontend on a REST API backed by Sequelize/MySQL, with Firebase Cloud Messaging for live updates.",
    features: [
      "Attendance",
      "Leave Management",
      "Employee Management",
      "Reports",
      "Notifications",
    ],
    tech: [
      "React.js",
      "Redux Toolkit",
      "React Query",
      "Node.js",
      "Sequelize",
      "MySQL",
      "Firebase",
    ],
    impact:
      "Digitized HR operations and delivered real-time employee notifications.",
  },
  {
    id: "multi-erp",
    name: "Multi-Domain ERP & Commerce Suite",
    company: "DI Solutions",
    problem:
      "Clients across manufacturing, medical, and retail needed ERP, POS, and e-commerce on a shared, maintainable codebase.",
    solution:
      "A modular ERP with POS and e-commerce on shared inventory, real-time updates, documented APIs, and multi-gateway payments.",
    architecture:
      "MVC Node/Express services with MySQL/Sequelize, Socket.IO for real-time flows, Swagger-documented APIs, and Razorpay/Stripe/PayPal checkout.",
    features: [
      "Inventory",
      "Purchase",
      "Sales",
      "Shipment",
      "Logistics",
      "POS",
      "E-commerce",
    ],
    tech: [
      "Node.js",
      "Express.js",
      "React.js",
      "MySQL",
      "Sequelize",
      "Socket.IO",
      "Stripe",
      "Razorpay",
      "PayPal",
      "Firebase",
      "Swagger",
    ],
    impact:
      "Delivered 10+ modules with multi-gateway checkout and real-time operations.",
  },
];

export const SKILL_GROUPS: { label: string; items: string[] }[] = [
  { label: "Languages", items: ["JavaScript", "TypeScript"] },
  { label: "Frontend", items: ["React.js", "Next.js", "Redux Toolkit", "React Query", "Tailwind CSS", "Bootstrap"] },
  { label: "Backend", items: ["Node.js", "Express.js", "REST APIs", "Socket.IO", "MVC Architecture"] },
  { label: "Database", items: ["MySQL", "MongoDB", "Redis", "Sequelize ORM", "Firebase"] },
  { label: "Authentication", items: ["JWT", "OAuth", "RBAC"] },
  { label: "Payments", items: ["Razorpay", "Stripe", "PayPal"] },
  { label: "DevOps & Cloud", items: ["Linux VPS", "NGINX", "PM2", "GitHub Actions", "CI/CD"] },
  { label: "Architecture", items: ["Multi-Tenant SaaS", "Dynamic DB Routing", "Tenant Isolation", "Caching", "Scalability"] },
  { label: "Tools & Testing", items: ["Git", "GitHub", "Postman", "Swagger"] },
];

/** Key engineering highlights — max 6, recruiter-impressing one-liners. */
export const HIGHLIGHTS: string[] = [
  "Architected a multi-tenant SaaS platform with per-tenant database isolation and dynamic, LRU-cached routing.",
  "Modeled 50+ normalized MySQL tables backing 10+ production ERP modules.",
  "Integrated 3 payment gateways (Razorpay, Stripe, PayPal) with secure webhook verification.",
  "Automated deployment on Linux VPS with NGINX, PM2 cluster mode, and GitHub Actions CI/CD.",
  "Implemented JWT + module-level RBAC across ERP, HRMS, and e-commerce systems.",
  "Built real-time features with Socket.IO and Firebase across multiple products.",
];

export const EDUCATION = [
  { degree: "Master of Computer Applications (MCA)", note: "Information Technology" },
  { degree: "Bachelor of Commerce (B.Com)", note: "" },
];
